### ISSUE TITLE
Filetype autocommands fail when plugin is loaded lazily

### ISSUE THREAD

**Issue by jfpedroza** [raimon49/requirements.txt.vim#38]
Having

```lua
use({ "raimon49/requirements.txt.vim", ft = "requirements" })
```

with Packer causes the following error when opening a file with no filetype:

    E117: Unknown function: requirements#shebang

Removing `ft = "requirements"` solves the issue.

It seems `autoload/requirements.nvim` is not loaded, so the function doesn't exist.

**Comment by Freed-Wu** [comment]
similar with #37. Can you provide a minimum vimrc without any other vim plugin (include package management)?

**Comment by Freed-Wu** [comment]
> It seems autoload/requirements.nvim is not loaded, so the function doesn't exist.

Can you update `requirements.txt.vim` plugin to latest? <https://github.com/raimon49/requirements.txt.vim/blob/master/autoload/requirements.vim> contains `requirements#shebang()` function. In original code, it has a typo, sometimes name it shabang, sometimes name it shebang. The name now has been unified to rename to shebang.

I can provide a minimum vimrc `test.vim` to prove it can work:

```vim
#!/usr/bin/env -S vi -u
set runtimepath=$VIMRUNTIME
set runtimepath+=~/.local/share/nvim/repos/github.com/raimon49/requirements.txt.vim
filetype on
```

```sh
$ chmod +x test.vim
$ cat requirements.txt
# Options
--allow-external
--allow-unverified

# Freeze packages
alabaster==0.7.6
$ ./test.vim requirements.txt
```

Result:

![Screenshot from 2023-08-24 15-41-09](https://github.com/raimon49/requirements.txt.vim/assets/32936898/22eaf602-9904-4a94-b92b-31925b13e144)

No any warning.

**Comment by jfpedroza** [comment]
Like mentioned in the title, the issue only happens when the plugin is loaded lazily. The plug is up-to-date.

I can reproduce with Neovim and Packer. I think it's because Packer uses a separate folder for optional plugins and doesn't load autoload files.

Here is a minimal `init.lua`. You can do `nvim --clean -u minimal.lua` and then `:e file`.

```lua
-- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.expand("~/.config/nvim"))
vim.opt.packpath:remove(vim.fn.expand("~/.local/share/nvim/site"))
vim.opt.termguicolors = true

-- append test directory
local test_dir = "/tmp/nvim-config"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
  vim.cmd("packadd packer.nvim")
  install_plugins = true
end

local packer = require("packer")

packer.init({
  package_root = test_dir .. "/pack",
  compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

packer.startup(function(use)
  use("wbthomason/packer.nvim")

  use({ "raimon49/requirements.txt.vim", ft = "requirements" })

  if install_plugins then
    packer.sync()
  end
end)

```

**Comment by Freed-Wu** [comment]
> the issue only happens when the plugin is loaded lazily

### I think this plugin doesn't need load lazy

Some vim plugin define many functions in `plugin/*.vim` which make vim slower.
A better practice is define commands in `plugin/*.vim` like `command XXX call foo#bar("xyz")` and define autoload functions `foo#bar()` in `autoload/foo.vim`.
Only when user use `:XXX`, vim will according `foo#bar()` to search `autoload/foo.vim` in `&runtimepath`, and source it. Otherwise, `autoload/foo.vim` will not be sourced to save users' time.

However, some vim plugin is old, and use a bad pratice: define many functions in `plugin/*.vim`. So we can use lazy load by plugin manager: We don't add this plugin to `&runtimepath` directly,
When some condition is trigger, we add it to `&runtimepath`. such as condition is 'filetype is XXX', it is `autocmd FileType XXX set runtimepath+=/the/path/of/old/plugin`.

This vim plugin doesn't contains any `plugin/*.vim`, so it is unnecessary to load it lazily.

### I think it is related to packer.nvim, Because I can use other plugin manager to install it.

I use dein.nvim as my plugin manager, An example to load lazily is:

```vim
set runtimepath=$VIMRUNTIME
set runtimepath+=~/.local/share/nvim/repos/github.com/Shougo/dein.vim
if dein#load_state(expand('~/.local/share/nvim'))
  call dein#begin(expand('~/.local/share/nvim'))
  call dein#add('Shougo/dein.vim')
  call dein#add('raimon49/requirements.txt.vim', {
        \ 'on_ft': 'requirements',
        \ })
  call dein#end()
  call dein#save_state()
endif
filetype on
```

```sh
git clone https://github.com/Shougo/dein.vim ~/.local/share/nvim/repos/github.com/Shougo/dein.vim
```

```vim
:call dein#install()
```

```sh
$ chmod +x test.vim
$ ./test.vim requirements.txt
```

I try it and found no any warning. Because lazy load: `'on_ft': 'requirements',`, it will work when users manually `set ft=requirement`.

I am not familiar with lua, however I think it is packer.nvim do some different behaviour with `dein.nvim`? Maybe you should ask the maintainer of packer.nvim to know why.

**Comment by jfpedroza** [comment]
> I think this plugin doesn't need load lazy

I agree. I think I copied the line mindlessly from somewhere and didn't consider if it really needed to be lazy-loaded.

I removed the lazy load.

I agree that it seems it's a specific issue with Packer, so we can consider this closed.

Thanks.
